### ISSUE TITLE
Unable to spawn actors in scenario_runner: after pull

### ISSUE THREAD

**Issue by Dhairyashil-kpit** [carla-simulator/scenario_runner#305] opened 2019-07-01 05:11 UTC
HI,

carla version: 0.9.5
python version: 3.5.2

I am able to connect to carla server via manual_control.py and it spawning the ego vehicle.

But for new changes of scenario runner, I am facing following errors. 

**1.  After taking pull of scenario runner branch, getting following error:** 

![Selection_002](https://user-images.githubusercontent.com/46476227/60411817-3547dd00-9bec-11e9-8a95-7260d8453e2e.png)

**2. From CarlaActorPool._world.try_spawn_actor() not able to spawn the actors into carla.**

3. Carla server is running as docker container with Town01 map

![Selection_003](https://user-images.githubusercontent.com/46476227/60411899-a4253600-9bec-11e9-8cc8-81146ab02bb5.png)

![Selection_004](https://user-images.githubusercontent.com/46476227/60412562-30385d00-9bef-11e9-8c05-0704a5483376.png)

**Comment by fabianoboril** [comment] 2019-07-01 06:09
Can you connect to CARLA at all? Did CARLA throw a message why the vehicle could not be spawned? Which Python version do you use? Just writing "Bug!!!!!!!!" does not really help to debug the issue.

**Comment by Dhairyashil-kpit** [comment] 2019-07-01 06:18
> Can you connect to CARLA at all? Did CARLA throw a message why the vehicle could not be spawned? Which Python version do you use? Just writing "Bug!!!!!!!!" does not really help to debug the issue.

Hi @fabianoboril , I updated the post, please check.
I am not able to detect the issue why scenario runner is not able to spawn the actors using CarlaActorPool._world.try_spawn_actor().

**Comment by fabianoboril** [comment] 2019-07-01 08:14
Does CARLA inform you about a collision when trying to spawn an actor? If yes, try to use the flag --waitForEgo when starting

**Comment by fabianoboril** [comment] 2019-07-01 09:30
And could you please run it with --debug  to get some further output? Thank you.

**Comment by fabianoboril** [comment] 2019-07-02 08:19
Should be fixed with #307

**Comment by fabianoboril** [comment] 2019-07-08 06:22
I am closing this issue, as it seems resolved. Please re-open, if the problem is still there.

**Closed by fabianoboril** 2019-07-08 06:22 UTC
