### ISSUE TITLE
IndexError: bytes to write exceed buffer size

### ISSUE THREAD

**Issue by iremonur** [carla-simulator/scenario_runner#715] opened 2020-12-31 09:51 UTC
Hi, I'm trying to use Scenario Runner to run the OpenScenario scenarios using manual_control.py. In separate terminals, I run the simulator, scenario_runner.py and manual control.py with these commands:

$ ./CarlaUE4.sh -opengl Town04
$ python scenario_runner.py --openscenario <path_to_scenario>
$ python manual_control.py

After i run manual_control.py, i got the IndexError:

Traceback (most recent call last):
  File "manual_control.py", line 550, in <lambda>
    self.sensor.listen(lambda image: CameraManager._parse_image(weak_self, image))
  File "manual_control.py", line 590, in _parse_image
    self._surface = pygame.surfarray.make_surface(array.swapaxes(0, 1))
  File "/usr/lib/python2.7/dist-packages/pygame/surfarray.py", line 243, in make_surface
    return numpysf.make_surface (array)
  File "/usr/lib/python2.7/dist-packages/pygame/_numpysurfarray.py", line 368, in make_surface
    blit_array (surface, array)
  File "/usr/lib/python2.7/dist-packages/pygame/_numpysurfarray.py", line 437, in blit_array
    surface.get_buffer ().write (data, 0)
IndexError: bytes to write exceed buffer size

Is this error related to GPU capability or something about scenario_runner? 

 - OS:  Ubuntu 18.04
 - CARLA Version: CARLA 0.9.9-50
 - Python version: 2.7
 - GPU: NVidia Quadro K3100M (GPU capability : 3.0)
 - Scenario runner version : 0.9.8

Is there any idea what could be causing this error?
Thank you for your help!

**Comment by glopezdiest** [comment] 2021-11-23 15:43
Hey, sorry for the delay. If I recall correctly, this was caused by the manual control lacking some world ticks, which didn't correctly set up the surface before trying to access it. This should be fixed so I'm closing the issue. Feel free to reopen it if you can still reproduce it

**Closed by glopezdiest** 2021-11-23 15:43 UTC
