### ISSUE TITLE
AttributeError: module 'carla' has no attribute 'Transform'

### ISSUE THREAD

**Issue by chowkamlee81** [carla-simulator/scenario_runner#19] opened 2019-01-05 13:02 UTC
When trying to execute python scenario_runner.py --scenario FollowLeadingVehicle
got the error below

Traceback (most recent call last):
  File "scenario_runner.py", line 22, in <module>
    from Scenarios.follow_leading_vehicle import *
  File "/home/deepaknayak/Documents/Reinforcement-learning/scenario_runner-master/Scenarios/follow_leading_vehicle.py", line 30, in <module>
    class FollowLeadingVehicle(BasicScenario):
  File "/home/deepaknayak/Documents/Reinforcement-learning/scenario_runner-master/Scenarios/follow_leading_vehicle.py", line 44, in FollowLeadingVehicle
    _ego_vehicle_start = carla.Transform(
AttributeError: module 'carla' has no attribute 'Transform'

**Comment by fabianoboril** [comment] 2019-01-06 07:42
Hi,
did you setup CARLA as described in the documentation, e.g. did you properly set the PYTHONPATH?
https://github.com/carla-simulator/scenario_runner/blob/master/Docs/getting_started.md#running-the-follow-vehicle-example

**Comment by fabianoboril** [comment] 2019-01-07 08:13
Hi,

when you just start python, which version does it print? 3.5 or 2.x? If it is 2.x, please update your PYTHONPATH to use the correct egg-file, or start the scenario with python3.

**Comment by fabianoboril** [comment] 2019-01-11 09:20
Any updates on this one? Is it resolved?

**Comment by geekhut** [comment] 2019-01-17 01:40
Try with python3:

`python3 scenario_runner.py --scenario FollowLeadingVehicle
`

**Comment by fabianoboril** [comment] 2019-01-23 18:14
I guess the problem is solved. I'll close the issue for now.

**Closed by fabianoboril** 2019-01-23 18:14 UTC
Labels: PythonAPI, solved
